# Config file for automatic testing at travis-ci.org
sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 2.7
install: 
  - ./travis_install.sh
before_script:
  - ./tests/installTestDb.sh
script: 
  - nose2 -v
branches:
  only:
  - unittest